using Discord;
using System.Text;
using ThaddeusMorrowind.Bot.Features.Inventory.Dtos;

namespace ThaddeusMorrowind.Bot.Discord.Views;

public static class Phase2AdvancedViews
{
    public static Embed Result(string title,string msg,bool ok)=>new EmbedBuilder().WithTitle(title).WithDescription(msg).WithColor(ok?Color.Green:Color.Red).WithCurrentTimestamp().Build();
    public static Embed Xp(CharacterXpDto x,string msg)=>new EmbedBuilder().WithTitle($"✨ XP de {x.CharacterName}").WithDescription(msg).AddField("Nivel",x.Level,true).AddField("XP actual",x.CurrentXp,true).AddField("XP total",x.TotalXp,true).AddField("Para siguiente",x.XpToNextLevel,true).WithColor(Color.Gold).Build();
    public static Embed Sets(IReadOnlyList<ArtifactSetDto> sets){var b=new EmbedBuilder().WithTitle("🏺 Sets de artefactos").WithColor(Color.Purple).WithFooter($"Sets: {sets.Count}").WithCurrentTimestamp(); if(sets.Count==0)return b.WithDescription("No encontré sets.").Build(); var t=new StringBuilder(); foreach(var s in sets.Take(12)){t.AppendLine($"**{s.Name}** `key:{s.SetKey}`");t.AppendLine($"Tipo `{s.SetType}` · Fuente `{s.SourceKey??"general"}`");t.AppendLine(s.TwoPieceSummary);t.AppendLine(s.FourPieceSummary);t.AppendLine();} return b.WithDescription(t.ToString()).Build();}
    public static Embed Set(ArtifactSetDto s){var b=new EmbedBuilder().WithTitle($"🏺 {s.Name}").WithDescription(s.Description??"Sin descripción.").AddField("Key",$"`{s.SetKey}`",true).AddField("Tipo",$"`{s.SetType}`",true).AddField("Fuente",$"`{s.SourceKey??"general"}`",true).WithColor(Color.Purple).WithCurrentTimestamp(); foreach(var bonus in s.Bonuses) b.AddField("Bono",bonus,false); return b.Build();}
    public static Embed Weapons(IReadOnlyList<WeaponDto> ws){var b=new EmbedBuilder().WithTitle("⚔️ Catálogo de armas").WithColor(Color.DarkRed).WithFooter($"Armas: {ws.Count}").WithCurrentTimestamp(); if(ws.Count==0)return b.WithDescription("No encontré armas.").Build(); var t=new StringBuilder(); foreach(var w in ws.Take(15)){t.AppendLine($"**{w.Name}** {Stars(w.Stars)} `key:{w.ItemKey}`");t.AppendLine($"Main: {w.MainStat??"?"} · Sec: {w.SecondaryStat??"?"}"); if(!string.IsNullOrWhiteSpace(w.Description)) t.AppendLine(w.Description.Length>150?w.Description[..150]+"...":w.Description); t.AppendLine();} return b.WithDescription(t.ToString()).Build();}
    public static Embed Weapon(WeaponDto w){var b=new EmbedBuilder().WithTitle($"⚔️ {w.Name} {Stars(w.Stars)}").WithDescription(w.Description??"Sin descripción.").AddField("Key",$"`{w.ItemKey}`",true).AddField("Principal plano",w.MainStat??"Pendiente",true).AddField("Secundario %",w.SecondaryStat??"Pendiente",true).WithColor(Color.DarkRed).WithCurrentTimestamp(); if(w.Passives.Count==0)b.AddField("Pasivas","Sin pasivas registradas.",false); else foreach(var p in w.Passives)b.AddField("Pasiva",p,false); return b.Build();}
    public static Embed Items(IReadOnlyList<ItemTemplateSearchDto> items){var b=new EmbedBuilder().WithTitle("🔎 Búsqueda de items").WithColor(Color.Blue).WithFooter($"Resultados: {items.Count}").WithCurrentTimestamp(); if(items.Count==0)return b.WithDescription("No encontré items.").Build(); var t=new StringBuilder(); foreach(var it in items.Take(20)){t.AppendLine($"**{it.Name}** {Stars(it.Stars)} `key:{it.ItemKey}`");t.AppendLine($"Cat `{it.CategoryKey}` · Tipo `{it.ItemSubtype??"general"}`"); if(!string.IsNullOrWhiteSpace(it.Description))t.AppendLine(it.Description.Length>120?it.Description[..120]+"...":it.Description);t.AppendLine();} return b.WithDescription(t.ToString()).Build();}
    public static Embed ArtifactXp(ArtifactXpDto x,string msg){var b=new EmbedBuilder().WithTitle($"🏺 {x.ItemName}").WithDescription(msg).AddField("Nivel",$"{x.OldLevel} → {x.NewLevel}/{x.MaxLevel}",true).AddField("XP",$"{x.OldXp} → {x.NewXp}",true).WithColor(Color.Purple).WithCurrentTimestamp(); b.AddField("Eventos",x.Events.Count==0?"Sin eventos.":string.Join("\n",x.Events.Take(10)),false); return b.Build();}
    public static Embed FinalStats(FinalStatsDto dto){var b=new EmbedBuilder().WithTitle($"📊 Stats finales de {dto.CharacterName}").WithDescription("Fórmula: **final = base + plano + ((base + plano) × porcentaje)**.").WithColor(Color.Teal).WithCurrentTimestamp(); var t=new StringBuilder(); foreach(var s in dto.Stats.Take(24))t.AppendLine($"**{s.Name}:** {Fmt(s.FinalValue,s.ValueKind)} `base {Fmt(s.BaseValue,s.ValueKind)} + plano {Fmt(s.FlatBonus,s.ValueKind)} + {s.PercentBonus:0.##}%`"); b.AddField("Desglose",t.ToString(),false); return b.Build();}
    private static string Stars(int? n)=>n is null or <=0?"":new string('★',n.Value); private static string Fmt(decimal v,string k)=>k.Equals("percent",StringComparison.OrdinalIgnoreCase)?$"{v:0.##}%":$"{v:0.##}";
}
